DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS owners CASCADE;
DROP TABLE IF EXISTS cars CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;


CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  phone_number VARCHAR(32) NOT NULL,
  location VARCHAR(255) NOT NULL,
  owner BOOLEAN DEFAULT FALSE,
  drivers_licence VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
);

CREATE TABLE owners (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES
)

CREATE TABLE cars (
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES owner(id) ON DELETE CASCADE,
  car_photo VARCHAR(255) NOT NULL,
  make VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  colour VARCHAR(255) NOT NULL,
  price_per_day DECIMAL NOT NULL,
  year DATE NOT NULL
);

CREATE TABLE bookings (
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES,
  cars_id INTEGER REFERENCES,
  user_id INTEGER REFERENCES,
  city VARCHAR(255) NOT NULL,
  booking_start DATE,
  booking_end DATE,
  good_state_start BOOLEAN DEFAULT TRUE,
  good_state_end BOOLEAN DEFAULT FALSE,
  deposit BOOLEAN DEFAULT FALSE,
  review_id INTEGER REFERENCES
);
